### ISSUE TITLE
NDHGO (RET:11) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#1148]
### on_search

- /message/catalog/bpp/providers/items/month_year_of_manufacture_packing_import should not have value '/'
- /message/catalog/bpp/providers/tags must have 'order_value'/'min_value'

### select

- /message/order/items/0 must have required property 'location_id'
- location_id should be same for the item MTMyNjY1XzgxMjAyNjFfM19Q as in on_search

### on_confirm

- np_type should be provided in /message/order/tags/bpp_terms

### on_status

- out-for-delivery status should be provided

### on_cancel

- updated_at provided in precancel_state should be valid as when state was last updated before cancellation

### on_cancel

- invalid quote provided

## Flow 6

- part-cancellation, reverse-qc, liquidation should be done in same order

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
@sahil-ondc Can you confirm the difference between `Order-picked-up` and `Out-for-delivery`?

**Comment by rajib-senrysa** [comment]
@sahil-ondc Can you explain more on Flow 6?

**Comment by rajib-senrysa** [comment]
@sahil-ondc Can you confirm how the quote is invalid in Flow 5? The `on_cancel`, has the old quote and the `on_status-rto-disposed` has the old quote. Can you please clarify?

**Comment by rajib-senrysa** [comment]
@sahil-ondc @BLR-0118 @sandeepshahi We have addressed these issues and resubmitted logs. Kindly check and review.

**Comment by rajib-senrysa** [comment]
@BLR-0118 @sandeepshahi Any update on this?

**Comment by rajib-senrysa** [comment]
@BLR-0118 @sandeepshahi @sahil-ondc Any update on this?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- what does circle.radius of 99999 km mean? (pl note that max radial distance of earth is ~6000 km);
- F&B doesn't have EAN code;
- F&B is supposed to be for fresh food, hence the following aren't appropriate:
- returnable true, return window of 3 days, cancellable true, statutory_reqs_packaged_commodities (only for packaged commodities);
- customization has to be enabled for F&B;

**Comment by BLR-0118** [comment]
@rajib-senrysa - pls resubmit for all flows after fixing the issues above;

**Comment by rajib-senrysa** [comment]
@BLR-0118 Is customization mandatory for this rollout?

**Comment by rajib-senrysa** [comment]
@BLR-0118 We will work on the customizations and submit it by max tomorrow. But the changes you have mentioned are only for /on_search right? Can you clear the transactional logs?

**Comment by rajib-senrysa** [comment]
@BLR-0118 If we send cancellable as false, How will we simulate Flow 4 (Buyer Side Cancellation)?

**Comment by rajib-senrysa** [comment]
@BLR-0118 @sahil-ondc @sandeepshahi We have raised the PR. Kindly merge and review

**Comment by rajib-senrysa** [comment]
@sandeepshahi Any update?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- pan-India / 3000 km serviceability for fresh food is invalid;
- all catalog items in F&B should have item type;
- not sure what display seq "0" in category_ids means?
- defn of item MTMyNjY1XzgxNTAzMDJfM19Q & other items with unitized weight should be defined as customizations (e.g. 500g / 1kg cake);
- not clear what max qty of 1 for any of the customizations mean, when there is no order cap for any of the base items;

**Comment by BLR-0118** [comment]
@rajib-senrysa - pls fix this & resubmit before other flows can be verified

**Comment by rajib-senrysa** [comment]
@BLR-0118 
`defn of item MTMyNjY1XzgxNTAzMDJfM19Q & other items with unitized weight should be defined as customizations (e.g. 500g / 1kg cake);`

Can you please explain this issue or provide an example?

**Comment by BLR-0118** [comment]
@rajib-senrysa - diff weights for F&B items need to be defined as customizations e.g. base item cake can have weight customization_group with customization definitions for 500g, 1kg; you can check how others have defined catalog for F&B from the GitHub log repo

**Comment by rajib-senrysa** [comment]
@BLR-0118 Whether a seller provides weight customizations for a product is up to the seller right? If a cake / biriyani is only available in 500g then we can’t provide any customizations for that correct?

**Comment by rajib-senrysa** [comment]
We have fixed the remaining issues and resubmitted /on_search. Please check @BLR-0118

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- in F&B, all (base) items should have unitized measure of 1 unit; any weight/volume to be shown, should be in the form of customizations e.g. item MTMyNjY1XzgxNTAyOThfM19Q & few others;

**Comment by BLR-0118** [comment]
@rajib-senrysa - this was mentioned earlier but not fixed; pls fix this & resubmit

**Comment by rajib-senrysa** [comment]
@BLR-0118 Resubmitted the Logs!

**Comment by Jagannath-wits** [comment]
# Flow 1

## Message

The message `/message/catalog/bpp/providers/items/tags/'type'` is optional for non-customizable (standalone) SKUs.

## Unitized Measure

The `unitized.measure` should include different unitized measures like kg, etc., and not just 1 unit, as a cake could be defined on weight, etc.

## Default Customization

The default customization must be set for the custom group with `config.min=1`.

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
> The message `/message/catalog/bpp/providers/items/tags/'type'` is optional for non-customizable (standalone) SKUs.

Since this is optional, It's not a problem if we include it right?



> The `unitized.measure` should include different unitized measures like kg, etc., and not just 1 unit, as a cake could be defined on weight, etc.

We were told to send 1 unit for all the F&B Product and if needed to show the weight we can include them as customizations.



> The default customization must be set for the custom group with `config.min=1`.

We have already defined the min in  the custom_group right?

**Comment by rajib-senrysa** [comment]
@Jagannath-wits Can you check and clarify these please?

**Comment by Jagannath-wits** [comment]
> > The message `/message/catalog/bpp/providers/items/tags/'type'` is optional for non-customizable (standalone) SKUs.
> 

Since this is optional it's better not to provide it when its not required

> 
> > The `unitized.measure` should include different unitized measures like kg, etc., and not just 1 unit, as a cake could be defined on weight, etc.
> 
> We were told to send 1 unit for all the F&B Product and if needed to show the weight we can include them as customizations.
> 

But as Cake is ordered as per size and not unit its better to provide weight and not unit

 @sandeepshahi please advise

**Comment by rajib-senrysa** [comment]
@Jagannath-wits For the first point will fix that. For the second point, can you please confirm what's the correct behaviour?

**Comment by rajib-senrysa** [comment]
@Jagannath-wits Is it mandatory to define variants for F&B?

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits Is it mandatory to define variants for F&B?

Yes , Varients are mandatory

**Comment by BLR-0118** [comment]
flow 1
====
1. /on_search:
- pls note that F&B is for fresh food; hence, statutory_reqs_packaged_commodities is invalid here;
- if store timings are same for all days, you need not send separate store timing per day;
- doesn't cover all test cases required (e.g. item base price of 0);

2. inc /on_search:
- only supports update of full item record & changing specific attrs for provider/location (enable/disable, etc);

flow 2
====
1. /on_select:
- tax line item missing;

2. /on_status:
- why is gps not being enabled in this case?

flow 3
====
1. /on_select_oos:
- error.message has item id which isn't in /select_oos;

**Comment by BLR-0118** [comment]
@rajib-senrysa - reviewed flows 1 to 3; multiple issues to be fixed, hence, not going forward;

**Comment by rajib-senrysa** [comment]
> > @Jagannath-wits Is it mandatory to define variants for F&B?
> 
> Yes , Varients are mandatory

If a merchant sells cake of only one weight, then how would we add it to the Variant Group? Should we create a Variant group with only one product? @Jagannath-wits @BLR-0118

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
-tax for MTMyNjY1XzgxNTAyOTJfM19Q not in quote;

2. Context.timestamp for all callback responses (/on_select, etc) is earlier than the corresponding request;
3. /on_init should have provider_tax_number in bpp_terms;
4. /on_track payload should be complete;

Flow 3
====
1. /on_select_oos:
- pls share example of customization out-of-stock;

**Comment by bmonish** [comment]
@BLR-0118 is tax for customization items mandatory?

**Comment by NishthaMonga** [comment]
### Flow 3
## on_select-oos
- Customisable item should be selected and that should be out of stock and error message should be encoded as "[{\"dynamic_item_id\":\"DI1\",\"item_id\":\"I1\",\"error\":\"40002\"}, {\"dynamic_item_id\":\"DI2\",\"customization_id\":\"C15\",\"customization_group_id\":\"CG3\",\"error\":\"40002\"}]
- Tags should not be empty in item object

### Flow 4
## on_cancel
- precancel_state.updated_at of on_cancel is not equal with the on_confirm order.updated_at

### Flow 5
## on_select
- context/timestamp difference between /on_select and /select should be less than 5 sec
- Warning: Quoted Price in /on_select INR 2190 does not match with the total price of items in /select INR 2170 i.e price for the item mismatch in on_search and on_select

## on_init
- context/timestamp difference between /on_init and /init should be less than 5 sec

## on_cancel
- /message/order/quote/breakup/0/item must have required property 'price'
- fulfillment type delivery start/contact/email is missing in /on_cancel
- RTO fulfillment start object  is missing in on_cancel
- RTOfulfillment.end": "RTO fulfillment end object  is missing in on_cancel
- additional delivery object in fulfillments
- precancel_state.updated_at of on_cancel is not equal with the on_status_out_for_delivery order.updated_at

## on_status calls missing

**Comment by rajib-senrysa** [comment]
@NishthaMonga Any update on this?

**Comment by sahil-ondc** [comment]
## Flow 1  

### on_search
- Items with the custom_menu '35' and '49' have same rank
- Days are not in the right order ‘5,1,7,2,6,4,3’, should be in sequence
- If the fulfillments are not provided in the bpp/providers/fulfillments, It should not be present in the bpp/fulfillments
- Default selection should be provided when the base item price is 0, for the item_id ‘MTM1MDIxXzY2YjA1YjVhNjQ0NzdlMTU4Y2FhN2EyM18zX1A=‘. Refer page no. 25 of the contract
- Default customisation is not set as config.min is 1  

## Flow 2
### on_select
- "item": {}, this not allowed in the quote.breakup

### on_init
- context/timestamp difference between /on_init and /init should be less than 5 sec
- tags[] can’t be empty like this in quote.breakup

### on_confirm
- Timestamp for /confirm api cannot be greater than or equal to /on_confirm api

### On Status Picked
- invoice should be publically accessible and accurate
### On Status Out For Delivery
- fulfillments/state Should be out-for-delivery for /on_status_Out-for-delivery
- timestamp for the start object in delivery fulfillment can’t be changed

## Flow 3, Flow 4
- Same as Flow 2

## Flow 5
Same as Flow 2

### On Status RTO Disposed
- fulfillment type delivery end/person is missing in /on_status_rto_delivered/disposed
- '@ondc/org/TAT' key is missing in the 'Delivery' fulfillment object of on_status_rto_disposed
- Mismatch occurred while comparing 'Delivery' fulfillment object with on_status_rto_disposed on key 'end/location/‘gps

## Flow 6
- Same as Flow 2

### Update Setllement Liquidated
context/timestamp of /update_settlement_liquidated should be greater than context/timestamp of /on_update_liquidated

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
@sahil-ondc 

Kindly clarify these issues.

1. If the bpp has multiple fulfillment types for different providers, shouldn't all the supported types be included in `bpp/fulfillments`?
2. We have limited resources in our pre-prod environment, hence the 5 second difference. But we have adequate resources in Prod and our average response time is 0.70 seconds.
3. Can you tell me the difference between Order-picked-up status and Order-out-for-delivery?
4. '@ondc/org/TAT' key is present in the Delivery fulfillment object.
5. The start and end will be swapped for RTO right? Start will be the customer location and end will be the store location.

**Comment by rajib-senrysa** [comment]
@BLR-0118 @sahil-ondc Kindly clarify these!

**Comment by BLR-0118** [comment]
2. ok;
3. out-for-delivery to be set when rider has reached delivery location;
4. ok;
5. RTO start may or may not be the customer location (could also be some interim point); end will be store location if package is being returned to store;

**Comment by BLR-0118** [comment]
log cleared for v1.2.0
